import { useEffect, useRef, useState } from "react";
import { Bold, Heading2, Heading3, ImagePlus, Link as LinkIcon, List, ListOrdered, Quote } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { BlogPost, BlogStatus } from "@/lib/blog";
import { calculateReadingMinutes, slugifyBlogTitle } from "@/lib/blog";

type FormValue = { id?: string; title: string; slug: string; excerpt: string; content: string; cover_image_url: string; category: string; author_name: string; status: BlogStatus; published_at: string; seo_title: string; seo_description: string };
const empty: FormValue = { title: "", slug: "", excerpt: "", content: "", cover_image_url: "", category: "CRM", author_name: "Echipa Habitoo", status: "draft", published_at: "", seo_title: "", seo_description: "" };
function fromPost(post: BlogPost | null): FormValue { return post ? { id: post.id, title: post.title, slug: post.slug, excerpt: post.excerpt, content: post.content, cover_image_url: post.cover_image_url ?? "", category: post.category, author_name: post.author_name, status: post.status, published_at: post.published_at?.slice(0,16) ?? "", seo_title: post.seo_title ?? "", seo_description: post.seo_description ?? "" } : empty; }

export function BlogEditor({ post, categories, busy, onCancel, onSave, onPreview, onUpload }: { post: BlogPost | null; categories: string[]; busy: boolean; onCancel: () => void; onSave: (value: FormValue) => void; onPreview: (value: FormValue) => void; onUpload: (file: File) => Promise<string> }) {
  const [form, setForm] = useState<FormValue>(() => fromPost(post)); const [slugEdited, setSlugEdited] = useState(!!post); const [uploading, setUploading] = useState(false); const contentRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { setForm(fromPost(post)); setSlugEdited(!!post); }, [post]);
  const set = (key: keyof FormValue, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const insert = (before: string, after = "", placeholder = "text") => { const el = contentRef.current; if (!el) return; const start = el.selectionStart; const end = el.selectionEnd; const selected = form.content.slice(start,end) || placeholder; set("content", `${form.content.slice(0,start)}${before}${selected}${after}${form.content.slice(end)}`); requestAnimationFrame(() => el.focus()); };
  const upload = async (file?: File) => { if (!file) return; setUploading(true); try { set("cover_image_url", await onUpload(file)); } finally { setUploading(false); } };
  return <form className="space-y-6" onSubmit={(event) => { event.preventDefault(); onSave(form); }}>
    <div className="grid gap-5 lg:grid-cols-2"><Field label="Titlu"><Input required value={form.title} onChange={(event) => { const title = event.target.value; setForm((current) => ({ ...current, title, slug: slugEdited ? current.slug : slugifyBlogTitle(title) })); }}/></Field><Field label="Slug"><Input required value={form.slug} onChange={(event) => { setSlugEdited(true); set("slug", slugifyBlogTitle(event.target.value)); }}/></Field></div>
    <Field label="Rezumat"><Textarea required maxLength={500} rows={3} value={form.excerpt} onChange={(event) => set("excerpt", event.target.value)}/></Field>
    <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Field label="Categorie"><Input required list="blog-categories" value={form.category} onChange={(event) => set("category", event.target.value)}/><datalist id="blog-categories">{categories.map((item) => <option key={item} value={item}/>)}</datalist></Field><Field label="Autor"><Input required value={form.author_name} onChange={(event) => set("author_name", event.target.value)}/></Field><Field label="Stare"><Select value={form.status} onValueChange={(value: BlogStatus) => set("status", value)}><SelectTrigger className="h-11"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="draft">Ciornă</SelectItem><SelectItem value="published">Publicat</SelectItem></SelectContent></Select></Field><Field label="Data publicării"><Input type="datetime-local" value={form.published_at} onChange={(event) => set("published_at", event.target.value)}/></Field></div>
    <Field label="Imagine de copertă"><div className="flex flex-col gap-3 sm:flex-row"><Input value={form.cover_image_url} onChange={(event) => set("cover_image_url", event.target.value)} placeholder="URL sau imagine încărcată"/><Button type="button" variant="outline" disabled={uploading} className="h-11 shrink-0" onClick={() => document.getElementById("blog-cover-upload")?.click()}><ImagePlus/> {uploading ? "Se încarcă…" : "Încarcă"}</Button><input id="blog-cover-upload" className="hidden" type="file" accept="image/jpeg,image/png,image/webp,image/svg+xml" onChange={(event) => void upload(event.target.files?.[0])}/></div>{form.cover_image_url ? <img src={form.cover_image_url} alt="Previzualizare copertă" className="mt-3 aspect-video max-w-lg rounded-xl border object-cover"/> : null}</Field>
    <Field label={`Conținut · ${calculateReadingMinutes(form.content)} min de citit`}><div className="mb-2 flex flex-wrap gap-2" aria-label="Formatare conținut"><Tool icon={Heading2} label="Titlu H2" onClick={() => insert("## ", "", "Titlu secțiune")}/><Tool icon={Heading3} label="Titlu H3" onClick={() => insert("### ", "", "Subtitlu")}/><Tool icon={Bold} label="Aldin" onClick={() => insert("**", "**")}/><Tool icon={List} label="Listă" onClick={() => insert("- ", "", "element")}/><Tool icon={ListOrdered} label="Listă numerotată" onClick={() => insert("1. ", "", "element")}/><Tool icon={Quote} label="Citat" onClick={() => insert("> ", "", "citat")}/><Tool icon={LinkIcon} label="Link" onClick={() => insert("[", "](https://)")}/><Tool icon={ImagePlus} label="Imagine" onClick={() => insert("![Descriere imagine](", ")", "https://")}/></div><Textarea ref={contentRef} required value={form.content} onChange={(event) => set("content", event.target.value)} className="min-h-[420px] resize-y font-mono text-sm leading-relaxed" placeholder="Scrie articolul folosind bara de formatare…"/></Field>
    <div className="grid gap-5 lg:grid-cols-2"><Field label="Titlu SEO"><Input maxLength={180} value={form.seo_title} onChange={(event) => set("seo_title", event.target.value)}/></Field><Field label="Descriere SEO"><Textarea maxLength={320} rows={2} value={form.seo_description} onChange={(event) => set("seo_description", event.target.value)}/></Field></div>
    <div className="flex flex-col-reverse gap-3 border-t pt-5 sm:flex-row sm:justify-end"><Button type="button" variant="ghost" onClick={onCancel}>Anulează</Button><Button type="button" variant="outline" onClick={() => onPreview(form)}>Previzualizează</Button><Button type="submit" disabled={busy}>{busy ? "Se salvează…" : "Salvează articolul"}</Button></div>
  </form>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function Tool({ icon: Icon, label, onClick }: { icon: typeof Bold; label: string; onClick: () => void }) { return <Button type="button" variant="outline" size="icon" className="size-11" title={label} aria-label={label} onClick={onClick}><Icon/></Button>; }
