import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { ArrowLeft } from "lucide-react";
import { BlogCover } from "@/components/blog/BlogCover";
import { Button } from "@/components/ui/button";
import { appHead } from "@/components/app/app-head";
import { getAdminBlogPost } from "@/lib/blog.functions";
import type { BlogPost } from "@/lib/blog";

export const Route = createFileRoute("/_authenticated/superadmin/blog/preview/$id")({ head: () => appHead("Habitoo CRM — previzualizare articol"), component: PreviewPage });
function PreviewPage() { const { id } = Route.useParams(); const load = useServerFn(getAdminBlogPost); const [local, setLocal] = useState<BlogPost | null>(null); useEffect(() => { if (id !== "new") return; const raw = sessionStorage.getItem("habitoo.blog.preview"); if (!raw) return; const value = JSON.parse(raw); setLocal({ ...value, id: "preview", reading_minutes: Math.max(1, Math.ceil(value.content.split(/\s+/).length / 200)), created_at: new Date().toISOString(), updated_at: new Date().toISOString(), contentHtml: simplePreview(value.content) }); }, [id]); const query = useQuery({ queryKey: ["superadmin", "blog", "preview", id], queryFn: () => load({ data: { id } }), enabled: id !== "new", retry: false }); const post = id === "new" ? local : query.data; if (!post) return <p className="p-8 text-muted-foreground">Se pregătește previzualizarea…</p>; return <div className="min-h-screen bg-background"><header className="sticky top-0 z-10 border-b bg-background/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-4"><Button asChild variant="ghost"><Link to="/superadmin/blog"><ArrowLeft/> Înapoi la editor</Link></Button><span className="rounded-full bg-warning/15 px-3 py-1 text-xs font-semibold text-warning-foreground">Previzualizare · nu este public</span></div></header><article className="mx-auto max-w-[760px] px-4 py-12"><span className="rounded-full bg-gold-tint px-3 py-1 text-xs font-semibold text-accent-foreground">{post.category}</span><h1 className="mt-5 font-display text-4xl font-semibold text-navy sm:text-5xl">{post.title}</h1><p className="mt-4 text-muted-foreground">{post.reading_minutes} min de citit · {post.author_name}</p><BlogCover src={post.cover_image_url} alt={`Copertă pentru ${post.title}`} eager className="mt-8 rounded-2xl"/><div className="blog-prose mt-10" dangerouslySetInnerHTML={{ __html: post.contentHtml ?? "" }}/></article></div>; }
function simplePreview(value: string) { return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^> (.+)$/gm,"<blockquote>$1</blockquote>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").split(/\n\n+/).map((part) => /^<(h2|h3|blockquote)/.test(part) ? part : `<p>${part.replace(/\n/g,"<br>")}</p>`).join(""); }
