ALTER TABLE public.properties
  ADD COLUMN IF NOT EXISTS comfort text,
  ADD COLUMN IF NOT EXISTS destination text,
  ADD COLUMN IF NOT EXISTS kitchens integer,
  ADD COLUMN IF NOT EXISTS balconies integer,
  ADD COLUMN IF NOT EXISTS terraces integer,
  ADD COLUMN IF NOT EXISTS floor_label text,
  ADD COLUMN IF NOT EXISTS orientation text,
  ADD COLUMN IF NOT EXISTS renovation_year integer,
  ADD COLUMN IF NOT EXISTS parking_spaces integer,
  ADD COLUMN IF NOT EXISTS garages integer,
  ADD COLUMN IF NOT EXISTS bathroom_window boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS open_kitchen boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS pet_friendly boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS key_in_agency boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS total_usable_surface numeric,
  ADD COLUMN IF NOT EXISTS balcony_surface numeric,
  ADD COLUMN IF NOT EXISTS terrace_surface numeric,
  ADD COLUMN IF NOT EXISTS garden_surface numeric,
  ADD COLUMN IF NOT EXISTS construction_stage text,
  ADD COLUMN IF NOT EXISTS building_type text,
  ADD COLUMN IF NOT EXISTS building_structure text,
  ADD COLUMN IF NOT EXISTS seismic_risk text,
  ADD COLUMN IF NOT EXISTS has_basement boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_semi_basement boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_ground_floor boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_attic boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_loft boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS recessed_floors integer,
  ADD COLUMN IF NOT EXISTS heating_systems text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS cooling_systems text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS finish_state text,
  ADD COLUMN IF NOT EXISTS insulation text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS wall_finishes text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS floor_finishes text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS windows text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS blinds text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS shutters text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS entry_door text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS interior_doors text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS additional_spaces text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS kitchen_features text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS metering text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS appliances text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS building_amenities text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS street_arrangement text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS views text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS misc_features text[] NOT NULL DEFAULT '{}';